/**
 * WHAT WE DO — 11 adımlı hizmet ekosistemi. Brief §13.4.
 *
 * Kural: adım başlıkları ve sloganlar HER DİLDE İngilizce kalır.
 * Sadece alt başlık, açıklama cümlesi ve madde listeleri çevrilir.
 */

import type { Locale } from "@/i18n/routing";

export type EcosystemStep = {
  /** "01" … "11" */
  number: string;
  /** Her dilde İngilizce kalır. */
  title: string;
  /** Yerel alt başlık. */
  subtitle: Record<Locale, string>;
  /** Tek cümlelik açıklama. */
  intro: Record<Locale, string>;
  bullets: Record<Locale, string[]>;
  /** Sadece 11. adımda: büyük tipografili soru bloğu. */
  highlight?: Record<Locale, string[]>;
};

export const ECOSYSTEM_INTRO: Record<Locale, string> = {
  en: "The Champ Global combines the manufacturing power of textiles with design, brand management, technology and e-commerce experience to deliver **an end-to-end creation and commerce system.** From the first analysis of an idea to fabric development; from building a collection to production; from packaging the product to positioning it in the right sales channel — we manage the entire process **within a single ecosystem.**",
  tr: "The Champ Global, tekstilin üretim gücünü; tasarım, marka yönetimi, teknoloji ve e-ticaret deneyimiyle birleştirerek **uçtan uca bir yaratım ve ticaret sistemi** sunar. Bir fikrin ilk analizinden, kumaşın geliştirilmesine; koleksiyonun oluşturulmasından üretime; ürünün paketlenmesinden doğru satış kanalında konumlandırılmasına kadar tüm süreci **tek bir ekosistem içerisinde yönetiyoruz.**",
  de: "The Champ Global verbindet die Fertigungskraft der Textilbranche mit Design, Markenführung, Technologie und E-Commerce-Erfahrung und liefert **ein durchgängiges Kreations- und Handelssystem.** Von der ersten Analyse einer Idee bis zur Stoffentwicklung; vom Aufbau einer Kollektion bis zur Produktion; von der Verpackung des Produkts bis zu seiner Positionierung im richtigen Vertriebskanal — wir steuern den gesamten Prozess **innerhalb eines einzigen Ökosystems.**",
  ar: "تجمع The Champ Global قوة التصنيع النسيجي مع التصميم وإدارة العلامات التجارية والتكنولوجيا وخبرة التجارة الإلكترونية لتقدّم **نظاماً متكاملاً للإبداع والتجارة.** من التحليل الأول للفكرة إلى تطوير القماش؛ ومن بناء المجموعة إلى الإنتاج؛ ومن تغليف المنتج إلى وضعه في قناة البيع الصحيحة — ندير العملية بأكملها **داخل منظومة واحدة.**",
};

export const ECOSYSTEM_STEPS: EcosystemStep[] = [
  {
    number: "01",
    title: "MARKET & CONSUMER INTELLIGENCE",
    subtitle: {
      en: "Market and consumer analysis",
      tr: "Pazar ve Tüketici Analizi",
      de: "Markt- und Konsumentenanalyse",
      ar: "تحليل السوق والمستهلك",
    },
    intro: {
      en: "We analyse shifting consumer behaviour, market dynamics, trends and sales data so that every collection answers a real need.",
      tr: "Değişen tüketici davranışını, pazar dinamiklerini, trendleri ve satış verilerini analiz ederiz; böylece her koleksiyon gerçek bir ihtiyaca cevap verir.",
      de: "Wir analysieren verändertes Konsumverhalten, Marktdynamik, Trends und Verkaufsdaten, damit jede Kollektion einen echten Bedarf beantwortet.",
      ar: "نحلّل سلوك المستهلك المتغيّر وديناميكيات السوق والاتجاهات وبيانات المبيعات، لتجيب كل مجموعة عن حاجة حقيقية.",
    },
    bullets: {
      en: [
        "Market and category analysis",
        "Consumer behaviour analysis",
        "Trend and demand analysis",
        "Evaluation of production & consumption data",
        "Product performance and sales data analysis",
      ],
      tr: [
        "Pazar ve kategori analizi",
        "Tüketici davranışı analizi",
        "Trend ve talep analizi",
        "Üretim & tüketim verilerinin değerlendirilmesi",
        "Ürün performansı ve satış verilerinin analizi",
      ],
      de: [
        "Markt- und Kategorieanalyse",
        "Analyse des Konsumentenverhaltens",
        "Trend- und Nachfrageanalyse",
        "Auswertung von Produktions- und Verbrauchsdaten",
        "Analyse von Produktleistung und Verkaufsdaten",
      ],
      ar: [
        "تحليل السوق والفئات",
        "تحليل سلوك المستهلك",
        "تحليل الاتجاهات والطلب",
        "تقييم بيانات الإنتاج والاستهلاك",
        "تحليل أداء المنتج وبيانات المبيعات",
      ],
    },
  },
  {
    number: "02",
    title: "BRAND & COLLECTION STRATEGY",
    subtitle: {
      en: "Brand and collection development",
      tr: "Marka ve Koleksiyon Geliştirme",
      de: "Marken- und Kollektionsentwicklung",
      ar: "تطوير العلامة التجارية والمجموعة",
    },
    intro: {
      en: "We turn an idea into a sustainable and scalable brand structure — from identity to collection architecture.",
      tr: "Bir fikri sürdürülebilir ve ölçeklenebilir bir marka yapısına dönüştürürüz — kimlikten koleksiyon mimarisine kadar.",
      de: "Wir verwandeln eine Idee in eine tragfähige und skalierbare Markenstruktur — von der Identität bis zur Kollektionsarchitektur.",
      ar: "نحوّل الفكرة إلى بنية علامة تجارية مستدامة وقابلة للتوسع — من الهوية إلى معمار المجموعة.",
    },
    bullets: {
      en: [
        "Brand creation and positioning",
        "Brand identity and product language",
        "Building collections on behalf of the brand",
        "Season and collection planning",
        "Product group and collection architecture",
        "Product strategy by target audience",
      ],
      tr: [
        "Marka oluşturma ve konumlandırma",
        "Marka kimliği ve ürün dili",
        "Marka adına koleksiyon oluşturma",
        "Sezon ve koleksiyon planlaması",
        "Ürün grubu ve koleksiyon mimarisi",
        "Hedef kitleye göre ürün stratejisi",
      ],
      de: [
        "Markenaufbau und Positionierung",
        "Markenidentität und Produktsprache",
        "Kollektionsaufbau im Namen der Marke",
        "Saison- und Kollektionsplanung",
        "Produktgruppen- und Kollektionsarchitektur",
        "Produktstrategie nach Zielgruppe",
      ],
      ar: [
        "بناء العلامة التجارية وتحديد موقعها",
        "هوية العلامة ولغة المنتج",
        "بناء المجموعات نيابة عن العلامة",
        "تخطيط المواسم والمجموعات",
        "معمار مجموعات المنتجات",
        "استراتيجية المنتج حسب الجمهور المستهدف",
      ],
    },
  },
  {
    number: "03",
    title: "FABRIC DEVELOPMENT",
    subtitle: {
      en: "Fabric development & textile R&D",
      tr: "Kumaş Geliştirme & Tekstil Ar-Ge",
      de: "Stoffentwicklung & Textil-F&E",
      ar: "تطوير القماش والبحث والتطوير النسيجي",
    },
    intro: {
      en: "We develop the fabric that defines the character of the product, driven by need and design.",
      tr: "Ürünün karakterini belirleyen kumaşı, ihtiyaç ve tasarım doğrultusunda geliştiririz.",
      de: "Wir entwickeln den Stoff, der den Charakter des Produkts bestimmt — getrieben von Bedarf und Design.",
      ar: "نطوّر القماش الذي يحدّد شخصية المنتج، انطلاقاً من الحاجة والتصميم.",
    },
    bullets: {
      en: [
        "Defining fabric type and structure",
        "Fabric composition development",
        "Knit and woven fabric solutions",
        "Weight, handfeel and surface properties",
        "Colour and fabric variations",
        "Product-specific fabric development",
        "Sampling and quality controls",
      ],
      tr: [
        "Kumaş cinsi ve yapısının belirlenmesi",
        "Kumaş kompozisyonu geliştirme",
        "Örme ve dokuma kumaş çözümleri",
        "Gramaj, tuşe ve yüzey özelliklerinin belirlenmesi",
        "Renk ve kumaş varyasyonları",
        "Ürüne özel kumaş geliştirme",
        "Numune ve kalite kontrolleri",
      ],
      de: [
        "Festlegung von Stoffart und -struktur",
        "Entwicklung der Stoffzusammensetzung",
        "Lösungen für Strick- und Webware",
        "Gewicht, Griff und Oberflächeneigenschaften",
        "Farb- und Stoffvarianten",
        "Produktspezifische Stoffentwicklung",
        "Bemusterung und Qualitätskontrollen",
      ],
      ar: [
        "تحديد نوع القماش وبنيته",
        "تطوير تركيب القماش",
        "حلول الأقمشة المحاكة والمنسوجة",
        "الوزن والملمس وخصائص السطح",
        "تنويعات اللون والقماش",
        "تطوير قماش خاص بالمنتج",
        "العينات وفحوصات الجودة",
      ],
    },
  },
  {
    number: "04",
    title: "DESIGN & PRODUCT DEVELOPMENT",
    subtitle: {
      en: "Design & product development",
      tr: "Tasarım & Ürün Geliştirme",
      de: "Design & Produktentwicklung",
      ar: "التصميم وتطوير المنتج",
    },
    intro: {
      en: "Instead of merely following trends, we translate them into products that fit the brand's DNA.",
      tr: "Trendleri yalnızca takip etmek yerine, markanın DNA'sına uyan ürünlere çeviririz.",
      de: "Statt Trends nur zu folgen, übersetzen wir sie in Produkte, die zur DNA der Marke passen.",
      ar: "بدلاً من مجرد اتّباع الاتجاهات، نترجمها إلى منتجات تناسب هوية العلامة.",
    },
    bullets: {
      en: [
        "Collection design",
        "Product design",
        "Graphic and print design",
        "Colour and material selection",
        "Sample development",
        "Defining product details",
        "Building collection coherence",
      ],
      tr: [
        "Koleksiyon tasarımı",
        "Ürün tasarımı",
        "Grafik ve baskı tasarımı",
        "Renk ve materyal seçimi",
        "Numune geliştirme",
        "Ürün detaylarının belirlenmesi",
        "Koleksiyon bütünlüğünün oluşturulması",
      ],
      de: [
        "Kollektionsdesign",
        "Produktdesign",
        "Grafik- und Druckdesign",
        "Farb- und Materialauswahl",
        "Musterentwicklung",
        "Festlegung der Produktdetails",
        "Aufbau der Kollektionskohärenz",
      ],
      ar: [
        "تصميم المجموعة",
        "تصميم المنتج",
        "تصميم الغرافيك والطباعة",
        "اختيار الألوان والخامات",
        "تطوير العينات",
        "تحديد تفاصيل المنتج",
        "بناء تناسق المجموعة",
      ],
    },
  },
  {
    number: "05",
    title: "PATTERN & PRE-PRODUCTION",
    subtitle: {
      en: "Pattern & pre-production preparation",
      tr: "Kalıp & Üretim Öncesi Hazırlık",
      de: "Schnitt & Produktionsvorbereitung",
      ar: "الباترون والتحضير لما قبل الإنتاج",
    },
    intro: {
      en: "We build the technical foundation of the designed product and make it ready for production.",
      tr: "Tasarlanan ürünün teknik altyapısını kurar ve onu üretime hazır hale getiririz.",
      de: "Wir schaffen die technische Grundlage des entworfenen Produkts und machen es produktionsreif.",
      ar: "نبني الأساس التقني للمنتج المصمَّم ونجعله جاهزاً للإنتاج.",
    },
    bullets: {
      en: [
        "Technical drawing and product file",
        "Pattern making",
        "Measurements and size grading",
        "Sample pattern",
        "Fitting sessions",
        "Pattern revisions",
        "Pre-production technical checks",
      ],
      tr: [
        "Teknik çizim ve ürün dosyası",
        "Kalıp oluşturma",
        "Ölçülendirme ve beden çalışmaları",
        "Numune kalıbı",
        "Fitting ve prova süreçleri",
        "Kalıp revizyonları",
        "Üretim öncesi teknik kontroller",
      ],
      de: [
        "Technische Zeichnung und Produktakte",
        "Schnitterstellung",
        "Vermaßung und Gradierung",
        "Musterschnitt",
        "Anproben",
        "Schnittrevisionen",
        "Technische Prüfungen vor der Produktion",
      ],
      ar: [
        "الرسم التقني وملف المنتج",
        "إعداد الباترون",
        "القياسات وتدرّج المقاسات",
        "باترون العينة",
        "جلسات القياس والبروفة",
        "مراجعات الباترون",
        "الفحوصات التقنية قبل الإنتاج",
      ],
    },
  },
  {
    number: "06",
    title: "PRODUCTION",
    subtitle: {
      en: "Cutting & sewing",
      tr: "Kesim & Dikim",
      de: "Zuschnitt & Näherei",
      ar: "القص والخياطة",
    },
    intro: {
      en: "We bring the developed collection to life in line with production standards.",
      tr: "Geliştirilen koleksiyonu üretim standartlarına uygun biçimde hayata geçiririz.",
      de: "Wir setzen die entwickelte Kollektion gemäß den Produktionsstandards um.",
      ar: "نحوّل المجموعة المطوَّرة إلى واقع وفق معايير الإنتاج.",
    },
    bullets: {
      en: [
        "Fabric spreading and marker preparation",
        "Cutting",
        "Panel inspection",
        "Sewing",
        "Coordination of production operations",
        "In-line quality controls",
        "Final product inspection",
      ],
      tr: [
        "Kumaş serim ve pastal hazırlığı",
        "Kesim",
        "Parça kontrolü",
        "Dikim",
        "Üretim operasyonlarının koordinasyonu",
        "Ara kalite kontrolleri",
        "Final ürün kontrolü",
      ],
      de: [
        "Stofflegen und Markervorbereitung",
        "Zuschnitt",
        "Teilekontrolle",
        "Näherei",
        "Koordination der Produktionsabläufe",
        "In-line-Qualitätskontrollen",
        "Endkontrolle des Produkts",
      ],
      ar: [
        "فرد القماش وتحضير المسطرة",
        "القص",
        "فحص القطع",
        "الخياطة",
        "تنسيق عمليات الإنتاج",
        "فحوصات الجودة أثناء الإنتاج",
        "الفحص النهائي للمنتج",
      ],
    },
  },
  {
    number: "07",
    title: "FINISHING & QUALITY",
    subtitle: {
      en: "Pressing, finishing & quality control",
      tr: "Ütü, Son İşlemler & Kalite Kontrol",
      de: "Bügeln, Finishing & Qualitätskontrolle",
      ar: "الكي والتشطيب ومراقبة الجودة",
    },
    intro: {
      en: "We don't only make the product — we make it ready for sale.",
      tr: "Ürünü yalnızca üretmiyoruz — satışa hazır hale getiriyoruz.",
      de: "Wir stellen das Produkt nicht nur her — wir machen es verkaufsfertig.",
      ar: "لا نصنع المنتج فحسب — بل نجعله جاهزاً للبيع.",
    },
    bullets: {
      en: [
        "Pressing and shaping",
        "Final product checks",
        "Measurement and appearance control",
        "Label and trim controls",
        "Quality standard verification",
        "Sale-ready product preparation",
      ],
      tr: [
        "Ütü ve form verme",
        "Son ürün kontrolleri",
        "Ölçü ve görünüm kontrolü",
        "Etiket ve aksesuar kontrolleri",
        "Ürün kalite standartlarının kontrolü",
        "Satışa hazır ürün hazırlığı",
      ],
      de: [
        "Bügeln und Formgebung",
        "Endkontrollen am Produkt",
        "Maß- und Erscheinungskontrolle",
        "Etiketten- und Zubehörkontrollen",
        "Überprüfung der Qualitätsstandards",
        "Verkaufsfertige Produktaufbereitung",
      ],
      ar: [
        "الكي وإعطاء الشكل",
        "الفحوصات النهائية للمنتج",
        "فحص القياس والمظهر",
        "فحص الملصقات والإكسسوارات",
        "التحقق من معايير الجودة",
        "تجهيز المنتج للبيع",
      ],
    },
  },
  {
    number: "08",
    title: "PACKAGING & FULFILLMENT",
    subtitle: {
      en: "Packaging & shipment preparation",
      tr: "Paketleme & Sevkiyata Hazırlık",
      de: "Verpackung & Versandvorbereitung",
      ar: "التغليف والتحضير للشحن",
    },
    intro: {
      en: "We treat the brand's final touchpoint with the customer as part of production itself.",
      tr: "Markanın müşteriyle son temas noktasını üretimin bir parçası olarak ele alırız.",
      de: "Wir behandeln den letzten Berührungspunkt der Marke mit dem Kunden als Teil der Produktion selbst.",
      ar: "نتعامل مع نقطة التماس الأخيرة بين العلامة والعميل كجزء من الإنتاج نفسه.",
    },
    bullets: {
      en: [
        "Product folding",
        "Labelling",
        "Packaging",
        "Order-based product preparation",
        "Pre-shipment inspection",
        "Logistics and operations coordination",
      ],
      tr: [
        "Ürün katlama",
        "Etiketleme",
        "Paketleme",
        "Sipariş bazlı ürün hazırlığı",
        "Sevkiyat öncesi kontrol",
        "Lojistik ve operasyon koordinasyonu",
      ],
      de: [
        "Produktfaltung",
        "Etikettierung",
        "Verpackung",
        "Auftragsbezogene Produktvorbereitung",
        "Kontrolle vor dem Versand",
        "Logistik- und Betriebskoordination",
      ],
      ar: [
        "طي المنتج",
        "الوسم والملصقات",
        "التغليف",
        "تجهيز المنتج حسب الطلب",
        "الفحص قبل الشحن",
        "تنسيق اللوجستيات والعمليات",
      ],
    },
  },
  {
    number: "09",
    title: "CHANNEL-BASED BRAND DESIGN",
    subtitle: {
      en: "Channel-specific brand & product structure",
      tr: "Satış Kanalına Özel Marka & Ürün Yapısı",
      de: "Kanalspezifische Marken- und Produktstruktur",
      ar: "بنية العلامة والمنتج حسب قناة البيع",
    },
    intro: {
      en: "Every sales channel has its own dynamic. We position brands according to the product, visual and commercial structure that channel demands.",
      tr: "Her satış kanalının kendi dinamiği vardır. Markaları, o kanalın talep ettiği ürün, görsel ve ticari yapıya göre konumlandırırız.",
      de: "Jeder Vertriebskanal hat seine eigene Dynamik. Wir positionieren Marken entsprechend der Produkt-, Bild- und Handelsstruktur, die dieser Kanal verlangt.",
      ar: "لكل قناة بيع ديناميكيتها الخاصة. نضع العلامات وفق بنية المنتج والصورة والتجارة التي تتطلبها تلك القناة.",
    },
    bullets: {
      en: [
        "Product strategy for e-commerce platforms",
        "Marketplace-focused brand structuring",
        "Channel-based collection planning",
        "Product title, content and visual strategy",
        "Price and product positioning",
        "Product optimisation by channel performance",
      ],
      tr: [
        "E-ticaret platformlarına özel ürün stratejisi",
        "Marketplace odaklı marka yapılanması",
        "Kanal bazlı koleksiyon planlaması",
        "Ürün başlığı, içerik ve görsel stratejisi",
        "Fiyat ve ürün konumlandırması",
        "Kanal performansına göre ürün optimizasyonu",
      ],
      de: [
        "Produktstrategie für E-Commerce-Plattformen",
        "Marktplatzorientierte Markenstrukturierung",
        "Kanalbezogene Kollektionsplanung",
        "Produkttitel-, Content- und Bildstrategie",
        "Preis- und Produktpositionierung",
        "Produktoptimierung nach Kanalleistung",
      ],
      ar: [
        "استراتيجية المنتج لمنصات التجارة الإلكترونية",
        "هيكلة العلامة بتركيز على الأسواق الإلكترونية",
        "تخطيط المجموعات حسب القناة",
        "استراتيجية عنوان المنتج والمحتوى والصور",
        "تحديد السعر وموقع المنتج",
        "تحسين المنتج وفق أداء القناة",
      ],
    },
  },
  {
    number: "10",
    title: "E-COMMERCE CONSULTING",
    subtitle: {
      en: "E-commerce consulting",
      tr: "E-Ticaret Danışmanlığı",
      de: "E-Commerce-Beratung",
      ar: "استشارات التجارة الإلكترونية",
    },
    intro: {
      en: "We don't stop at making the product — we get it to the right customer through the right channel.",
      tr: "Ürünü üretmekle yetinmiyoruz — doğru kanaldan doğru müşteriye ulaştırıyoruz.",
      de: "Wir hören nicht bei der Herstellung auf — wir bringen das Produkt über den richtigen Kanal zum richtigen Kunden.",
      ar: "لا نتوقف عند صناعة المنتج — بل نوصله إلى العميل المناسب عبر القناة المناسبة.",
    },
    bullets: {
      en: [
        "E-commerce brand strategy",
        "Digital store structuring",
        "Product and category optimisation",
        "Sales channel management",
        "Campaign and season planning",
        "E-commerce performance analysis",
        "Product development driven by sales data",
      ],
      tr: [
        "E-ticaret marka stratejisi",
        "Dijital mağaza yapılanması",
        "Ürün ve kategori optimizasyonu",
        "Satış kanalı yönetimi",
        "Kampanya ve sezon planlaması",
        "E-ticaret performans analizi",
        "Satış verilerine göre ürün geliştirme",
      ],
      de: [
        "E-Commerce-Markenstrategie",
        "Aufbau des digitalen Shops",
        "Produkt- und Kategorieoptimierung",
        "Management der Vertriebskanäle",
        "Kampagnen- und Saisonplanung",
        "Analyse der E-Commerce-Performance",
        "Produktentwicklung auf Basis von Verkaufsdaten",
      ],
      ar: [
        "استراتيجية العلامة في التجارة الإلكترونية",
        "هيكلة المتجر الرقمي",
        "تحسين المنتجات والفئات",
        "إدارة قنوات البيع",
        "تخطيط الحملات والمواسم",
        "تحليل أداء التجارة الإلكترونية",
        "تطوير المنتج وفق بيانات المبيعات",
      ],
    },
  },
  {
    number: "11",
    title: "DATA, PRODUCTION & CONSUMPTION ANALYSIS",
    subtitle: {
      en: "Data-driven production & consumption management",
      tr: "Veri Odaklı Üretim & Tüketim Yönetimi",
      de: "Datengetriebene Produktions- und Verbrauchssteuerung",
      ar: "إدارة الإنتاج والاستهلاك المعتمدة على البيانات",
    },
    intro: {
      en: "We use the data generated from production to sale in order to develop the collections of tomorrow.",
      tr: "Üretimden satışa kadar oluşan veriyi, yarının koleksiyonlarını geliştirmek için kullanırız.",
      de: "Wir nutzen die Daten von der Produktion bis zum Verkauf, um die Kollektionen von morgen zu entwickeln.",
      ar: "نستخدم البيانات الناتجة من الإنتاج حتى البيع لتطوير مجموعات الغد.",
    },
    highlight: {
      en: ["What was produced? What sold? What was in demand?", "What should be produced again? Which product found its market?"],
      tr: ["Ne üretildi? Ne satıldı? Neye talep vardı?", "Ne tekrar üretilmeli? Hangi ürün pazarını buldu?"],
      de: ["Was wurde produziert? Was wurde verkauft? Was war gefragt?", "Was sollte erneut produziert werden? Welches Produkt hat seinen Markt gefunden?"],
      ar: ["ماذا أُنتج؟ ماذا بِيع؟ على ماذا كان الطلب؟", "ما الذي يجب إنتاجه مجدداً؟ أي منتج وجد سوقه؟"],
    },
    bullets: {
      en: ["By analysing this data we continuously improve production planning, collections and product strategy."],
      tr: ["Bu verileri analiz ederek üretim planlamasını, koleksiyonları ve ürün stratejilerini sürekli geliştiriyoruz."],
      de: ["Durch die Analyse dieser Daten verbessern wir Produktionsplanung, Kollektionen und Produktstrategie kontinuierlich."],
      ar: ["بتحليل هذه البيانات نحسّن باستمرار تخطيط الإنتاج والمجموعات واستراتيجية المنتج."],
    },
  },
];
